# Generated by Django 4.0.6 on 2022-07-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_address', models.CharField(max_length=50)),
                ('emp_contact_number', models.CharField(max_length=50)),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.employeedepartment')),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.employeerole')),
            ],
        ),
    ]
